#define MyAppName "Secret Agent Man"
#define MyAppVersion "1.0"
#define MyAppPublisher "Havet Software"
#define MyAppURL "https://secretagentman.80tal.se/"
#define MyAppExeName "SecretAgentManLoader.exe"

[Setup]
AppId={{F24FEF15-2160-4FA4-90EC-839C688F7EBB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=D:\SecretAgentManSetup
OutputBaseFilename=InstallSecretAgentMan
SetupIconFile=D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\secretagentman.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Run]
Filename: "{app}\CheckNet.exe"; StatusMsg: "Checking for .NET 8.0-Windows"; Flags: skipifsilent

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentManLoader\bin\Release\net8.0-windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentManLoader\bin\Release\net8.0-windows\AxInterop.WMPLib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentManLoader\bin\Release\net8.0-windows\havet-logo.mp4"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentManLoader\bin\Release\net8.0-windows\Interop.WMPLib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentManLoader\bin\Release\net8.0-windows\SecretAgentManLoader.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentManLoader\bin\Release\net8.0-windows\SecretAgentManLoader.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentManLoader\bin\Release\net8.0-windows\SecretAgentManLoader.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Accessibility.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-console-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-datetime-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-debug-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-errorhandling-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-file-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-file-l1-2-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-file-l2-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-handle-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-heap-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-interlocked-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-libraryloader-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-localization-l1-2-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-memory-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-namedpipe-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-processenvironment-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-processthreads-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-processthreads-l1-1-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-profile-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-rtlsupport-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-string-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-synch-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-synch-l1-2-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-sysinfo-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-timezone-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-core-util-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-conio-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-convert-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-environment-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-filesystem-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-heap-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-locale-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-math-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-multibyte-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-private-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-process-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-runtime-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-stdio-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-string-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-time-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\api-ms-win-crt-utility-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\apphost.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\BroncoSettingsParser.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\clrcompression.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\clretwrc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\clrgc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\clrjit.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\config.bronco"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\coreclr.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\createdump.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\D3DCompiler_47_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\dbgshim.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\DirectWriteForwarder.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\hostfxr.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\hostpolicy.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Microsoft.CSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Microsoft.DiaSymReader.Native.amd64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Microsoft.VisualBasic.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Microsoft.VisualBasic.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Microsoft.VisualBasic.Forms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Microsoft.Win32.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Microsoft.Win32.Registry.AccessControl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Microsoft.Win32.Registry.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Microsoft.Win32.SystemEvents.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\MonoGame.Framework.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\mscordaccore.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\mscordaccore_amd64_amd64_4.6.30411.01.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\mscordaccore_amd64_amd64_8.0.2125.47513.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\mscordbi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\mscorlib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\mscorrc.debug.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\mscorrc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\msquic.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\netstandard.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PenImc_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationCore.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationFramework-SystemCore.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationFramework-SystemData.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationFramework-SystemDrawing.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationFramework-SystemXml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationFramework-SystemXmlLinq.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationFramework.Aero.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationFramework.Aero2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationFramework.AeroLite.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationFramework.Classic.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationFramework.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationFramework.Luna.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationFramework.Royale.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationNative_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\PresentationUI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\ReachFramework.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\RetroGame.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SecretAgentMan.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SecretAgentMan.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SecretAgentMan.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SecretAgentMan.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SharpDX.Direct2D1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SharpDX.Direct3D11.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SharpDX.Direct3D9.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SharpDX.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SharpDX.DXGI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SharpDX.Mathematics.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SharpDX.MediaFoundation.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SharpDX.XAudio2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SharpDX.XInput.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\sos.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\SOS.NETCore.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\sos_amd64_amd64_4.6.30411.01.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.AppContext.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Buffers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.CodeDom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Collections.Concurrent.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Collections.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Collections.Immutable.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Collections.NonGeneric.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Collections.Specialized.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.ComponentModel.Annotations.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.ComponentModel.DataAnnotations.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.ComponentModel.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.ComponentModel.EventBasedAsync.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.ComponentModel.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.ComponentModel.TypeConverter.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Configuration.ConfigurationManager.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Configuration.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Console.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Data.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Data.DataSetExtensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Data.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Design.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Diagnostics.Contracts.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Diagnostics.Debug.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Diagnostics.DiagnosticSource.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Diagnostics.EventLog.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Diagnostics.EventLog.Messages.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Diagnostics.FileVersionInfo.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Diagnostics.PerformanceCounter.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Diagnostics.Process.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Diagnostics.StackTrace.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Diagnostics.TextWriterTraceListener.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Diagnostics.Tools.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Diagnostics.TraceSource.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Diagnostics.Tracing.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.DirectoryServices.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Drawing.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Drawing.Design.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Drawing.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Drawing.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Dynamic.Runtime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Formats.Asn1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Formats.Tar.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Globalization.Calendars.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Globalization.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Globalization.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.Compression.Brotli.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.Compression.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.Compression.FileSystem.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.Compression.Native.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.Compression.ZipFile.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.FileSystem.AccessControl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.FileSystem.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.FileSystem.DriveInfo.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.FileSystem.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.FileSystem.Watcher.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.IsolatedStorage.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.MemoryMappedFiles.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.Packaging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.Pipes.AccessControl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.Pipes.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.IO.UnmanagedMemoryStream.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Linq.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Linq.Expressions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Linq.Parallel.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Linq.Queryable.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.Http.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.Http.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.HttpListener.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.Mail.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.NameResolution.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.NetworkInformation.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.Ping.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.Quic.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.Requests.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.Security.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.ServicePoint.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.Sockets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.WebClient.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.WebHeaderCollection.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.WebProxy.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.WebSockets.Client.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Net.WebSockets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Numerics.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Numerics.Vectors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.ObjectModel.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Printing.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Private.CoreLib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Private.DataContractSerialization.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Private.Uri.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Private.Xml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Private.Xml.Linq.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Reflection.DispatchProxy.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Reflection.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Reflection.Emit.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Reflection.Emit.ILGeneration.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Reflection.Emit.Lightweight.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Reflection.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Reflection.Metadata.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Reflection.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Reflection.TypeExtensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Resources.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Resources.Reader.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Resources.ResourceManager.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Resources.Writer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.CompilerServices.VisualC.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.Handles.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.InteropServices.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.InteropServices.JavaScript.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.InteropServices.RuntimeInformation.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.InteropServices.WindowsRuntime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.Intrinsics.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.Loader.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.Numerics.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.Serialization.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.Serialization.Formatters.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.Serialization.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.Serialization.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Runtime.Serialization.Xml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.AccessControl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Claims.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Cryptography.Algorithms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Cryptography.Cng.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Cryptography.Csp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Cryptography.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Cryptography.Encoding.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Cryptography.OpenSsl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Cryptography.Pkcs.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Cryptography.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Cryptography.ProtectedData.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Cryptography.X509Certificates.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Cryptography.Xml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Permissions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Principal.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.Principal.Windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Security.SecureString.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.ServiceModel.Web.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.ServiceProcess.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Text.Encoding.CodePages.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Text.Encoding.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Text.Encoding.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Text.Encodings.Web.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Text.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Text.RegularExpressions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Threading.AccessControl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Threading.Channels.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Threading.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Threading.Overlapped.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Threading.Tasks.Dataflow.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Threading.Tasks.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Threading.Tasks.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Threading.Tasks.Parallel.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Threading.Thread.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Threading.ThreadPool.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Threading.Timer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Transactions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Transactions.Local.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.ValueTuple.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Web.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Web.HttpUtility.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Windows.Controls.Ribbon.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Windows.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Windows.Forms.Design.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Windows.Forms.Design.Editors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Windows.Forms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Windows.Forms.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Windows.Input.Manipulations.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Windows.Presentation.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Xaml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Xml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Xml.Linq.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Xml.ReaderWriter.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Xml.Serialization.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Xml.XDocument.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Xml.XmlDocument.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Xml.XmlSerializer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Xml.XPath.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\System.Xml.XPath.XDocument.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\ucrtbase.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\UIAutomationClient.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\UIAutomationClientSideProviders.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\UIAutomationProvider.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\UIAutomationTypes.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\vcruntime140_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\WindowsBase.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\WindowsFormsIntegration.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\wpfgfx_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\ammo4x7.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\ammobox16x11.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\background-640x91.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\bomb40x31.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\bonus-meter.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\bonus-stars-640x360.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\bonuslevel.wma"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\bonuslevel.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\briefcase13x10.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\c64fontswe.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\coin10x10.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\crt.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\cutscene.wma"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\cutscene.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\cutsceneframe.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\enemy_sfx_coin_1.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\enemy_sfx_coin_2.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\enemy_sfx_coin_3.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\floppy.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\frame.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\game-over.wma"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\game-over.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\gameover1.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\gameover2.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\gameover3.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\gameover4.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\hiscore.wma"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\hiscore.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\hud.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\ingame.wma"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\ingame.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\lives11x7.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\load-screen-360p-nofilter.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\loader.wma"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\loader.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\mayor50x50.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\plane5x3.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\planeflipped5x3.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\player25x25.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\player_sfx_coin_1.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\player_sfx_coin_2.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\rip25x25.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_enemydeath1.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_enemydeath2.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_enemydeath3.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_gun1.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_gun10.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_gun2.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_gun3.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_gun4.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_gun5.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_gun6.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_gun7.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_gun8.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_gun9.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_noammo2.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_pickup-ammo.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sfx_playerdeath.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\sky-640x91.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\skyline_bg-640x91.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\skyline_fg-640x91.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\start-screen-frame.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\start-screen-gun.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\start-screen-logo433x54.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\start-screen-portraits.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\Static50x50.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\static_mayor.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\title_anim-465x205x5x17.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion
Source: "D:\GitRepos\Secret-Agent-Man\SecretAgentMan\SecretAgentMan\bin\Release\net8.0-windows\win-x64\Content\water640x30.xnb"; DestDir: "{app}\Content"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
